mastodon: 
  instance: mstdn.jp
  oauth_uri: mstdn.jp/oauth
  api_uri: mstdn.jp/api/v1
  streaming_uri: streaming.mstdn.jp/api/v1/streaming
  user_name: konn
  client_id: 128809
  client_key: "Client Key for Mastodon App"
  client_secret: "Client Secret for Mastodon App"
  access_token: "Access Token for Mastodon App"

twitter:
  consumer_key: "Twitter Consumer Key"
  consumer_secret: "Twitter Consumer Secret"
  access_token: "Twitter Access Token"
  access_token_secret: "Twitter Access Token Secret"

template: |
  {{content}} [亡命Mastodonより： {{url}}]
